export const FETCHING_HOME_DETAILS = 'FETCHING_HOME_DETAILS';
export const FETCHING_HOME_DETAILS_SUCCESS = 'FETCHING_HOME_DETAILS_SUCCESS';
export const FETCHING_HOME_DETAILS_FAILURE = 'FETCHING_HOME_DETAILS_FAILURE';
